### ISSUE TITLE
testing out Fiddle but getting an error

### ISSUE THREAD

**Issue by jhavenz** [brucemcpherson/cUseful#1]
Hi Bruce,

I'm trying out Fiddler for the first time and I'm trying to walk through one of your tutorials. I've setup a very simple test to read some data with fiddler but I keep getting this error when Im running it...

SyntaxError: Unexpected token for (line 704, file "Utils", project "cUseful")

This is my simple test script:

function myFunction() {
  
// get some data
  var sheetValues = SpreadsheetApp
    .openById('mysheetsID')
    .getSheetByName('Data')
    .getDataRange()
    .getValues();
  
  var fiddler = new cUseful.Fiddler();
  
  var values = fiddler.setValues(sheetValues);
  var data = fiddler.getData();
  
  Logger.log(data)
}

This is a snapshot of the test data I'm using..
![sample-bank-data](https://user-images.githubusercontent.com/53377590/77712218-70671900-6f90-11ea-87a7-df1a63705031.PNG)

Any help would be greatly appreciated. Fiddler looks like a pleasure to use.

**Comment by brucemcpherson** [comment]
Thanks for noticing this. I assume you are using the v8 - there's something
in there that v8 doesnt like the syntax of - I'll have to check it out and
tweak it. Fiddler doesn't even use that function, but it's making the whole
library non-v8 compatible. It should all be fine under non-v8.

**Comment by brucemcpherson** [comment]
OK - this is fixed in version 117.

**Comment by jhavenz** [comment]
Awesome. Thanks Bruce.
Yes, I was using V8. 
Really appreciate your assistance and contributions. Look forward to using them.
