### ISSUE TITLE
Additional GAS V8 error..

### ISSUE THREAD

**Issue by jhavenz** [brucemcpherson/cUseful#2]
Hi Bruce,
Its me stopping by again. 
When trying out your cDbAbstraction library as stated in this slideshow... 
(https://docs.google.com/presentation/d/10rEyXjHxo42YV3wRW46o-CgrAZxFqUxyftHPkjLtbt8/edit#slide=id.g4849056f7_078)

I ran this code and got another "Utils" error...
Here's the error: 
SyntaxError: Unexpected token for (line 704, file "Utils", project "cDbAbstraction.cUseful")

And Here's the code I was trying to run:
function test_dbAbstraction() {
  
  // open spreadsheet as database
  var handler = new cDbAbstraction.DbAbstraction (cDriverSheet, {
        siloid:'carrierCodes',
        dbid:'1ynCQ_xtxIBHGH_hEnUlZ_ivlF1DpmJCzkJdWQANFuD0',
  });
  if (!handler.isHappy()) throw 'unable to open sheet';

  // do a query
  var result = handler.query ({carrier:'UA'});
  if (result.handleCode < 0) throw result.handleError;
  Logger.log(result.data);

  
  // add a new record
  
  // do a query and sort and limit
  
  // delete added record
  
  // count query
}

This time though, I knew to try it on the legacy apps script and it worked. So it seems as if its just a v8 thing.

**Comment by brucemcpherson** [comment]
Is this still a thing - just checked the libraries and they seem to be using the v8 compatible version of cUseful. thanks
