### ISSUE TITLE
Error with sortFiddler reordering columns

### ISSUE THREAD

**Issue by shapeseas** [brucemcpherson/cUseful#5]
Today I was updating some scripts and I noticed that sortFiddler has some unintended side effects. I have columns ordered in a particular way, and then when I call sortFiddler it sorts the rows as intended BUT it also resorts the column order. See attached - this log is only from calling sortFiddler("Name") and then GPS and then Side. This wasn't a behavior I was seeing in the past so could it be a V8 issue?
![sortFiddler_issues](https://user-images.githubusercontent.com/63021088/96741571-f238ec80-138f-11eb-8c86-24e5ed449a45.png)

As an aside, I love this library. I've been using it regularly for a few years to pipe data at a small, independent high school in the states.

UPDATE: I tested on deprecated and v8 and that didn't make a difference in the behavior.

**Comment by brucemcpherson** [comment]
Thanks - i'll take a look.

**Comment by brucemcpherson** [comment]
Yes I can see how this might happen - I use fiddler.setData() after doing a sort, which regenerates the headers and therefore sets the column order - although it should be in the same order as the  keys in the original unsorted object (not guaranteed according to the specification - http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf - but for all practical purposes it always has been). 

I could probably guarantee the order using es6 map, but then it would break the legacy stuff, so another approach might be to detect if this is an already known order and use that. I'd like to understand why it shuffled it first though. 
Did you use any insert/delete column type operations, make any changes to the data returned by getData() from the time of creating the fiddler to the time of sorting it?

.. thanks for yor comments about the library. I must admit I've seldom had to bothe with native get/setValues since I wrote this thing several years ago now.

**Comment by shapeseas** [comment]
Yes, I use insertColumn. I'm joining two fiddlers - one with demographic data and one with grade data. I don't create a third fiddler, I simply update the grade fiddler with demographic fiddler info and order the columns and sort the rows so they can be written to a sheet (see steps below). As you can see below, the columns are ordered correctly after the 3rd step. But after sorting by row, the column order reverts to the original. Based on your assessment of the issue, I simply switched the order columns operation to the end and the output is correct.

Same - I like it so much I built a few operations that expand fiddler - things like pivot, unpivot, join. This library has really upped my speed which is especially important because it's only me doing this kind of work at my org. I tell everyone I know developing in Apps Script to use it - Google really should adopt it!


Operations:
1. Insert the GPS, Side, Activity, IEP columns (all coming from demographic fiddler) in the fiddler that has the grade data.
2. Update the values in those columns in the grade fiddler -  basically a join operation or vlookup. 
3. Order the columns by how I want them to appear on the sheet
4. Sort the rows by how I want them to appear on the sheet

Log:
[20-10-25 14:33:53:335 EDT] after insert: Name,Career Development - Career Portfolio 1,Elective - Future Focused Elective,Language Arts - Telling Your Story,Math - Financial Literacy,Research - Intro to Advocacy,Senior Project - Part I Foundations,GPS,Side,Activity Status,IEP Status

[20-10-25 14:33:53:956 EDT] after join: Name,Career Development - Career Portfolio 1,Elective - Future Focused Elective,Language Arts - Telling Your Story,Math - Financial Literacy,Research - Intro to Advocacy,Senior Project - Part I Foundations,GPS,Side,Activity Status,IEP Status

[20-10-25 14:33:53:958 EDT] after ordering columns: Name,GPS,Side,Activity Status,IEP Status,Language Arts - Telling Your Story,Math - Financial Literacy,Research - Intro to Advocacy,Senior Project - Part I Foundations,Elective - Future Focused Elective,Career Development - Career Portfolio 1

[20-10-25 14:33:54:000 EDT] after sorting rows: Name,Career Development - Career Portfolio 1,Elective - Future Focused Elective,Language Arts - Telling Your Story,Math - Financial Literacy,Research - Intro to Advocacy,Senior Project - Part I Foundations,GPS,Side,Activity Status,IEP Status

**Comment by brucemcpherson** [comment]
Ok - that makes sense - it shouldn't be that hard to guide the order
setData generates its map on if detects that the fiddler already has an
order involving the same properties as the data it is being asked to be
replaced. I'll see if I can find some time to do that.

Congrats on those extensions - if you'd like to write some articles on what
you've done I'm happy to credit you and publish them on my site. We perhaps
could even integrate some of them into the fiddler library.

cheers
bruce

**Comment by brucemcpherson** [comment]
Ok - please try with the latest version of the cUseful library - it attempts to preserve order on setData if it can.

**Comment by shapeseas** [comment]
The latest version works perfectly, thank you. sortFiddler retains the column order after multiple insertions and movement of columns.

I'm still early in my coding journey so my methods aren't nearly as clean as yours, but I'd love to share in an article! Let me know the best way to do that.

**Comment by brucemcpherson** [comment]
Just write it up and send it to me.  - I'll post it here
https://ramblings.mcpher.com/guests-articles-and-postings/

and reference it here
https://ramblings.mcpher.com/google-apps-scripts-snippets-2/afunctionalapproachtofiddlingwithsheetdata/

**Comment by shapeseas** [comment]
Thank you! I will take a look and get back to you.

I've been using the updated cUseful library, and any scripts that use setData to set the data of an empty fiddler now fail. It results in TypeError: Cannot convert undefined or null to object (line 1430): 
`const hk = Object.keys(headerOb_);`

I think the issue is that headerOb_ is undefined still when using setData on an empty fiddler so Object.keys() does not work.
Maybe this fix would work?
`if (!headerOb_) { headerOb_ = proposedHeader } `
`const ok = Object.keys(proposedHeader);`
`const hk = Object.keys(headerOb_);`
`if ( !preserveOrder || hk.length !== ok.length || ok.some(function (t) { return hk.indexOf(t) === -1; })) {
      headerOb_ = proposedHeader
} `

I'm not sure the etiquette on this, so if you'd like me to open another issue let me know.

**Comment by brucemcpherson** [comment]
This is fixed in 2.8.8 - thanks for noticing.
