### ISSUE TITLE
getHeadersBetween not getting headers correctly

### ISSUE THREAD

**Issue by shapeseas** [brucemcpherson/cUseful#6]
Hey thanks again for all your work on cUseful. I think I found another bug and (hopefully) also the solution so you won't have to spend much time fixing it.

**The problem:** I was using getHeadersBetween and it was producing an unusual result - whenever the start index is between 2 - 9 and the finishIndex goes above 10, it sorts backwards (see below). I think this is because .sort is converting the indexes into Strings first and then sorting ([see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort): "The default sort order is ascending, built upon converting the elements into strings, then comparing their sequences of UTF-16 code units values.")

just sort()
Oct 26, 2020, 9:17:00 PM startIndex: 1
Oct 26, 2020, 9:17:00 PM finishIndex: 11
Oct 26, 2020, 9:17:00 PM [s,f]: 1,11

Oct 26, 2020, 9:17:00 PM startIndex: 2
Oct 26, 2020, 9:17:00 PM finishIndex: 11
Oct 26, 2020, 9:17:00 PM [s,f]: 11,2

Oct 26, 2020, 9:17:00 PM startIndex: 9
Oct 26, 2020, 9:17:00 PM finishIndex: 11
Oct 26, 2020, 9:17:00 PM [s,f]: 11,9

Oct 26, 2020, 9:17:00 PM startIndex: 10
Oct 26, 2020, 9:17:00 PM finishIndex: 11
Oct 26, 2020, 9:17:00 PM [s,f]: 10,11

**The simple fix:** Supply sort with a comparator function: function(a,b) { return a - b }
This fixed it on my end, see result below. It is line 1007 that I think needs to be reworked:
`var [s,f] = [startIndex, finishIndex].sort(function(a,b) { return a - b });`

sort(function(a,b) { return a - b });
Oct 26, 2020, 9:15:39 PM startIndex: 1
Oct 26, 2020, 9:15:39 PM finishIndex: 11
Oct 26, 2020, 9:15:39 PM [s,f]: 1,11

Oct 26, 2020, 9:15:39 PM startIndex: 2
Oct 26, 2020, 9:15:39 PM finishIndex: 11
Oct 26, 2020, 9:15:39 PM [s,f]: 2,11

Oct 26, 2020, 9:15:39 PM startIndex: 9
Oct 26, 2020, 9:15:39 PM finishIndex: 11
Oct 26, 2020, 9:15:39 PM [s,f]: 9,11

Oct 26, 2020, 9:15:39 PM startIndex: 10
Oct 26, 2020, 9:15:39 PM finishIndex: 11
Oct 26, 2020, 9:15:39 PM [s,f]: 10,11

**Comment by brucemcpherson** [comment]
Yes - that would only work if the strings were convertible to numbers -
which they happen to be in your case. The default comparison function

    var compareFunc = options.compareFunc || function(a, b) {
      return a > b ? 1 : (a === b ? 0 : -1);
    };

Would work for both numbers and strings. Is it because the data you're
passing to it is in fact a string, rather than a number?

**Comment by shapeseas** [comment]
I'm using getHeadersBetween directly from cUseful and passing header names (strings) as arguments. Below are the results I get with getHeadersBetween with different header combinations using the current version of cUseful.

You'll notice that the **bolded rows** return an empty array even though they shouldn't - I think this is because of the issue I pointed out in previous comment. Before line 1007, the index of the fiddler headers "GPS" is 2 and "Student Connections" is 11 (which are determined in lines 1003,1004 self.getHeaderIndex). But when sorted as strings on line 1007, s is set to 11 and  f is setto 2. So when line 1008 is called, it returns an empty array because what's being called on self.getHeaders() is slice(11,2), not slice (2,11).
    `1007 var [s,f] = [startIndex, finishIndex].sort ();`
    `1008 var list = self.getHeaders().slice (s,f+1);`

Initial test of getHeadersBetween in cUseful, no comparator function passed to sort

`All headers: ID,Name,GPS,Side,Activity Status,Graduation Track,Success Coordinator,Counselor,Mentor,Alumni Mentor,Staff Connections,Student Connections,IEP Status,IEP Type,IEP Liaison,Parent Status,Incentive Status,Picture,Grant,Email,DOB,Reading Pre-Test,Math Pre-Test,Squad,M Email,S Email,S,A Email`

- `getHeadersBetween(Name,Student Connections): Name,GPS,Side,Activity Status,Graduation Track,Success Coordinator,Counselor,Mentor,Alumni Mentor,Staff Connections,Student Connections`
- **`getHeadersBetween(GPS,Student Connections):`**
- **`getHeadersBetween(Alumni Mentor,Student Connections): `**
- `getHeadersBetween(Staff Connections,Student Connections): Staff Connections,Student Connections`

In order to correct this, I made a simple modification to getHeadersBetween, adding the comparator function for numbers. The output seems to be corrected. And because startIndex and finishIndex will always be numbers (they are determined by getHeaderIndex), there should be a number comparator. 

Tests with modified getHeadersBetween with comparator function passed to sort

- `getHeadersBetween(Name,Student Connections): Name,GPS,Side,Activity Status,Graduation Track,Success Coordinator,Counselor,Mentor,Alumni Mentor,Staff Connections,Student Connections`
- **`getHeadersBetween(GPS,Student Connections): GPS,Side,Activity Status,Graduation Track,Success Coordinator,Counselor,Mentor,Alumni Mentor,Staff Connections,Student Connections`**
- **`getHeadersBetwen(Alumni Mentor,Student Connections): Alumni Mentor,Staff Connections,Student Connections`**
- `getHeadersBetween(Staff Connections,Student Connections): Staff Connections,Student Connections`

**Comment by brucemcpherson** [comment]
Thanks for this - I'll get to it shortly.

**Comment by brucemcpherson** [comment]
Thank you for this. You may not have seen this notice about moving to v8

https://github.com/brucemcpherson/desktopliberation/issues/54
fiddler is now in it's own library (and should contain a fix for this bug here)

I'm freezing the cUseful version so please flip over to bmFiddler when you have time
There's also some new stuff 
https://ramblings.mcpher.com/vuejs-apps-script-add-ons/fiddler-fingerprint/
