### ISSUE TITLE
Error when reading a property from a file which hasn't got any 

### ISSUE THREAD

**Issue by deltagolf** [brucemcpherson/cUseful#7]
First, let me thank you for your work. I'm starting to use it and play around with it and it is very helpful for dealing with properties in the Drive API. One of the errors I have encountered is when I try to get or read the properties of a file which hasn't got any. GAS throws this error

```
TypeError: Cannot read property 'filter' of undefined
DriveProper.self.get	@ DriveProper.gs:46
testGetProps	@ main.gs:43
```

The _testGetProps_ is my function, which calls yours.

**Comment by brucemcpherson** [comment]
Thanks for noticing this - I can see why that would happen. 
```` 
return service_.Files.get(fileId)
    .properties.filter
````
I'll patch it up tomorrow.

**Comment by brucemcpherson** [comment]
Patched in lib v132

return (service_.Files.get(fileId)
    .properties || []).filter
