### ISSUE TITLE
TypeError: Assignment to constant variable. in Rough.gs

### ISSUE THREAD

**Issue by benbeyerlein** [brucemcpherson/cUseful#9]
I'm following [this](https://ramblings.mcpher.com/gassnippets2/roughly-matching-text/) post to implement rough matching. So far I've replicated the test data in Sheets and the code snippets in GAS. When I execute the test, I get the following error:

TypeError: Assignment to constant variable.
(anonymous)	@ Rough.gs:156
scorer	@ Rough.gs:147
(anonymous)	@ Rough.gs:90
Rough.self.matcher	@ Rough.gs:87
roughMatchFunction	@ RoughMatch.gs:44

The code in use is below (the last line is line 44 in my RoughMatch.gs script file):
```
function roughMatchFunction() {

 const CLEANER_OPTIONS = {
    stem: true,
    stub: true ,
    unAccent: true,
    stopwords: true,
    language: "en",
    extraStops:[],
    min:0.6,
    scores: {
      stubMatch: 10,
      stubPenalty: -1,
      stemMatch: 12,
      stemPenalty: -1,
      wordMatch: 20 ,
      wordPenalty: -1,
      orderMatch: 1,
      stubPartialMatch: 40,
      stubPartialPenalty: -7,
      initialMatch: 3,
      initialPenalty: -4,
      reverseMatch: 2,
      reversePenalty: -4
    }
	};

var fiddler = new cUseful.Fiddler(SpreadsheetApp.getActiveSpreadsheet().getSheetByName("films")); //films
  var data = fiddler.getData();
    
  // build a reference list of names
  var rough = new cUseful.Rough().init({
    min:0.3
    //CLEANER_OPTIONS
  }).setReferenceList (data, function(row) {
    return row.trackName;
  });

  Logger.log (rough.getReferenceList());

// find things
  Logger.log (rough.matcher ("hunt october")[0].row.phrase);
}
```

Is there something wrong in the testing function or within rough.gs itself?

**Comment by brucemcpherson** [comment]
Hi Ben

Hard to debug this without your actual code. Share the sheet you are using
and code with me and I'll have a look

cheers
bruce

**Comment by brucemcpherson** [comment]
My email is ***@***.*** - you can reply to me directly.

**Comment by benbeyerlein** [comment]
Hi Bruce,
Your email didn't come through so I've shared the sheet as a link
<https://docs.google.com/spreadsheets/d/1O-GFesc9MiFVv1mIp_yharRGLl10EnB-iaEtEhiivlQ/edit?usp=sharing>
.

Thanks

**Comment by brucemcpherson** [comment]
Hi Ben

it was a bug in the library - use the latest version of cUseful and you
should be okay. btw in your logger statements check to see if there are any
matches before using them as references in case there were no good matches
found.

thanks for the feedback

bruce

**Comment by benbeyerlein** [comment]
Thanks for the library update and suggestion!
